### ISSUE TITLE
Crash when sorting items in Applied Energistics 2

### ISSUE THREAD

**Issue by Laruae** [P3pp3rF1y/Reliquary#203]
When sorting items by modID my server shut down giving the following error message in the crash report.

java.lang.ClassCastException: xreliquary.items.ItemVoidTear$VoidTearListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at appeng.container.implementations.ContainerMEMonitorable.func_75142_b(ContainerMEMonitorable.java:193)
	at appeng.container.implementations.ContainerPatternTerm.func_75142_b(ContainerPatternTerm.java:456)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:254)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:648)
	at net.minecraft.world.World.func_72939_s(World.java:1726)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

[crash-2016-12-25_04.41.11-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/672124/crash-2016-12-25_04.41.11-server.txt)

Very real possibility that this is an Applied Energistics 2 issue.

**Comment by P3pp3rF1y** [comment]
That is ae2 issue. But that was resolved a long time ago. You also seem to have a very old version of ae2 so updating should fix it.
