### ISSUE TITLE
oddness noticed in console(1.11.2)Reliquary-1.11.2-1.3.3.635

### ISSUE THREAD

**Issue by SDUBZ** [P3pp3rF1y/Reliquary#221]
forge:1.11.2-2232
reliquary: Reliquary-1.11.2-1.3.3.635

Error caught from Recipe Category: xreliquary.compat.jei.alkahestry.AlkahestryCraftingRecipeCategory
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_121]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_121]
	at xreliquary.compat.jei.alkahestry.AlkahestryCraftingRecipeCategory.setRecipe(AlkahestryCraftingRecipeCategory.java:60) ~[AlkahestryCraftingRecipeCategory.class:?]
	at xreliquary.compat.jei.alkahestry.AlkahestryCraftingRecipeCategory.setRecipe(AlkahestryCraftingRecipeCategory.java:16) ~[AlkahestryCraftingRecipeCategory.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.<init>(RecipeLayout.java:85) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:190) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:405) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:450) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.nextRecipeCategory(RecipeGuiLogic.java:205) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_146284_a(RecipesGui.java:369) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452) [bho.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73864_a(RecipesGui.java:300) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542) [bho.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_146274_d(RecipesGui.java:275) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510) [bho.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695) [bes.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:20:19] [Server thread/DEBUG] [FML/]: The world 40f7a636 (TEST) may have leaked: seen 335 times.

**Comment by P3pp3rF1y** [comment]
Thanks for reporting. Turns out I have probably not tested JEI integration well enough - had two indexes reversed.
