### ISSUE TITLE
Storm Shot Causes Client Crash and not able to log back into world

### ISSUE THREAD

**Issue by tspayne87** [P3pp3rF1y/Reliquary#222]
I am unable to log back into my minecraft server after shooting the storm shot into the sky,  I also shot 2 creepers before this which resulted in both times crashing the client.  Here is the report after trying to log back into the game for the fourth time.

```pre
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at xreliquary.entities.shot.EntityShotBase.getColor(EntityShotBase.java:281)
	at xreliquary.entities.shot.EntityShotBase.spawnPotionParticles(EntityShotBase.java:267)
	at xreliquary.entities.shot.EntityShotBase.func_70071_h_(EntityShotBase.java:189)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: xreliquary.entityStormShot (xreliquary.entities.shot.EntityStormShot)
	Entity ID: 11345269
	Entity Name: entity.xreliquary.entityStormShot.name
	Entity's Exact location: 173.35, 985.79, 270.68
	Entity's Block location: World: (173,985,270), Chunk: (at 13,61,14 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.05, 1.20, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['NamtarTheWicked'/11345651, l='MpServer', x=212.97, y=66.00, z=277.44]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (24,64,192), Chunk: (at 8,4,0 in 1,12; contains blocks 16,0,192 to 31,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 35091536 game time, 40448259 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 97 total; [EntitySpider['Spider'/11345824, l='MpServer', x=270.00, y=63.00, z=257.97], EntityPig['Pig'/281, l='MpServer', x=144.27, y=64.00, z=218.54], EntityPig['Pig'/283, l='MpServer', x=135.34, y=64.00, z=263.51], EntityPig['Pig'/284, l='MpServer', x=141.50, y=65.00, z=278.24], EntityPig['Pig'/298, l='MpServer', x=150.46, y=70.00, z=201.05], EntityPig['Pig'/300, l='MpServer', x=157.43, y=70.00, z=197.98], EntityPig['Pig'/303, l='MpServer', x=146.50, y=65.00, z=268.30], EntitySkeleton['Skeleton'/11345821, l='MpServer', x=265.73, y=68.00, z=298.48], EntityPig['Pig'/11345820, l='MpServer', x=264.45, y=68.00, z=294.67], EntityZombie['Zombie'/11345823, l='MpServer', x=268.35, y=29.00, z=282.35], EntityCreeper['Creeper'/11345822, l='MpServer', x=266.50, y=29.00, z=282.50], EntitySquid['Squid'/11345819, l='MpServer', x=256.23, y=61.00, z=235.60], EntityPig['Pig'/11345818, l='MpServer', x=269.38, y=63.00, z=241.71], EntityPlayerSP['NamtarTheWicked'/11345651, l='MpServer', x=212.97, y=66.00, z=277.44], EntitySkeleton['Skeleton'/11345812, l='MpServer', x=260.50, y=32.00, z=306.50], EntityBat['Bat'/11345809, l='MpServer', x=267.20, y=17.04, z=320.79], EntityCreeper['Creeper'/11345811, l='MpServer', x=242.50, y=25.00, z=324.50], EntityCow['Cow'/11345810, l='MpServer', x=264.78, y=66.00, z=326.51], EntityCreeper['Creeper'/11345900, l='MpServer', x=286.50, y=48.00, z=355.50], EntitySpider['Spider'/11345896, l='MpServer', x=287.50, y=28.00, z=320.50], EntityCreeper['Creeper'/11345893, l='MpServer', x=288.17, y=64.00, z=307.58], EntityZombie['Zombie'/11345895, l='MpServer', x=286.50, y=28.00, z=321.50], EntitySkeleton['Skeleton'/11345894, l='MpServer', x=284.79, y=28.00, z=321.36], EntitySkeleton['Skeleton'/11345891, l='MpServer', x=291.60, y=29.00, z=313.09], EntityPig['Pig'/11345916, l='MpServer', x=276.69, y=63.00, z=280.69], EntityZombie['Zombie'/11345913, l='MpServer', x=274.50, y=31.00, z=280.50], EntitySheep['Sheep'/11345915, l='MpServer', x=286.32, y=63.00, z=276.80], EntityZombie['Zombie'/11345914, l='MpServer', x=277.50, y=31.00, z=286.21], EntityPig['Pig'/7021364, l='MpServer', x=152.59, y=64.00, z=218.23], EntityBat['Bat'/11345885, l='MpServer', x=272.60, y=18.63, z=347.60], EntitySkeleton['Skeleton'/11345886, l='MpServer', x=292.33, y=29.00, z=332.53], EntitySkeleton['Skeleton'/11345881, l='MpServer', x=280.50, y=64.00, z=312.67], EntitySkeleton['Skeleton'/11345880, l='MpServer', x=277.29, y=36.00, z=313.21], EntityCow['Cow'/11345882, l='MpServer', x=287.53, y=64.00, z=319.78], EntitySkeleton['Skeleton'/11345877, l='MpServer', x=277.50, y=20.00, z=312.50], EntityCow['Cow'/11345876, l='MpServer', x=292.43, y=66.00, z=300.45], EntityZombie['Zombie'/11345879, l='MpServer', x=283.50, y=28.00, z=318.50], EntityZombie['Zombie'/11345878, l='MpServer', x=273.20, y=17.00, z=318.48], EntityPig['Pig'/6957289, l='MpServer', x=155.70, y=69.00, z=252.26], EntityPig['Pig'/11345705, l='MpServer', x=173.49, y=64.00, z=225.22], EntityPig['Pig'/11345704, l='MpServer', x=169.28, y=64.00, z=233.50], EntitySpider['Spider'/11345707, l='MpServer', x=136.50, y=33.00, z=270.50], EntityBat['Bat'/11345706, l='MpServer', x=189.84, y=31.64, z=209.87], EntityEnderman['Enderman'/11345701, l='MpServer', x=192.50, y=30.00, z=214.50], EntityCreeper['Creeper'/11345700, l='MpServer', x=192.50, y=31.00, z=212.50], EntityPig['Pig'/11345703, l='MpServer', x=194.78, y=69.00, z=206.51], EntityPig['Pig'/11345702, l='MpServer', x=185.71, y=64.00, z=238.47], EntityPig['Pig'/11345697, l='MpServer', x=174.65, y=64.00, z=208.79], EntityPig['Pig'/2665097, l='MpServer', x=149.67, y=69.00, z=251.95], EntityZombie['Zombie'/11345679, l='MpServer', x=223.28, y=68.00, z=286.87], EntityPig['Pig'/11345928, l='MpServer', x=281.84, y=62.06, z=261.70], EntityPig['Pig'/11345927, l='MpServer', x=275.66, y=63.00, z=262.75], EntityBat['Bat'/11346183, l='MpServer', x=196.50, y=12.00, z=251.50], EntityBat['Bat'/11345692, l='MpServer', x=189.75, y=33.68, z=198.95], EntitySkeleton['Skeleton'/11345689, l='MpServer', x=190.50, y=22.00, z=197.50], EntitySkeleton['Skeleton'/11345688, l='MpServer', x=182.50, y=22.00, z=197.50], EntityBat['Bat'/11345691, l='MpServer', x=190.10, y=33.02, z=199.60], EntityCreeper['Creeper'/11345690, l='MpServer', x=189.50, y=22.00, z=198.50], EntityZombie['Zombie'/11345687, l='MpServer', x=185.50, y=22.00, z=197.50], EntityPig['Pig'/11345772, l='MpServer', x=226.25, y=64.00, z=235.44], EntityWitch['Witch'/11345775, l='MpServer', x=227.24, y=67.00, z=291.79], EntitySquid['Squid'/11345774, l='MpServer', x=240.79, y=59.98, z=216.65], EntityBabySkeleton['Baby Skeleton'/11345769, l='MpServer', x=245.92, y=62.33, z=233.75], EntitySquid['Squid'/11345768, l='MpServer', x=248.71, y=58.15, z=228.68], EntityPig['Pig'/10190173, l='MpServer', x=143.67, y=65.00, z=273.42], EntitySquid['Squid'/11345771, l='MpServer', x=239.40, y=57.94, z=231.60], EntitySquid['Squid'/11345770, l='MpServer', x=243.84, y=62.07, z=225.50], EntityPig['Pig'/2676192, l='MpServer', x=143.52, y=65.00, z=261.73], EntityPig['Pig'/11345765, l='MpServer', x=224.75, y=69.00, z=199.50], EntityCreeper['Creeper'/11345767, l='MpServer', x=241.50, y=58.00, z=232.50], EntityZombie['Zombie'/11345766, l='MpServer', x=238.07, y=54.00, z=252.34], EntityPig['Pig'/11345277, l='MpServer', x=202.25, y=68.00, z=348.51], EntityPig['Pig'/11345276, l='MpServer', x=192.58, y=66.00, z=302.82], EntityPig['Pig'/11345279, l='MpServer', x=201.25, y=70.00, z=336.49], EntityPig['Pig'/11345278, l='MpServer', x=199.55, y=68.00, z=343.55], EntityPig['Pig'/11345273, l='MpServer', x=177.73, y=64.00, z=354.42], EntitySkeleton['Skeleton'/11345785, l='MpServer', x=193.50, y=16.00, z=321.50], EntityPig['Pig'/11345272, l='MpServer', x=188.45, y=63.65, z=318.53], EntityPig['Pig'/11345275, l='MpServer', x=201.83, y=65.00, z=294.50], EntityStormShot['entity.xreliquary.entityStormShot.name'/11345269, l='MpServer', x=173.35, y=985.79, z=270.68], EntityPig['Pig'/11345781, l='MpServer', x=241.31, y=69.00, z=292.73], EntitySkeleton['Skeleton'/11345268, l='MpServer', x=181.50, y=32.00, z=242.50], EntitySkeleton['Skeleton'/11345780, l='MpServer', x=225.50, y=17.00, z=335.50], EntityPig['Pig'/11345271, l='MpServer', x=179.50, y=62.47, z=306.45], EntitySpider['Spider'/11345783, l='MpServer', x=194.50, y=16.00, z=321.50], EntityPig['Pig'/11345270, l='MpServer', x=182.73, y=64.00, z=283.41], EntityCow['Cow'/11345777, l='MpServer', x=225.82, y=68.00, z=285.81], EntityItem['item.item.rottenFlesh'/11345776, l='MpServer', x=229.85, y=67.00, z=273.39], EntityCreeper['Creeper'/11345779, l='MpServer', x=236.50, y=16.00, z=322.50], EntityPig['Pig'/11345778, l='MpServer', x=243.28, y=67.00, z=312.81], EntityPig['Pig'/11339077, l='MpServer', x=156.53, y=71.00, z=206.74], EntityPig['Pig'/11345749, l='MpServer', x=231.71, y=65.00, z=343.45], EntityBat['Bat'/11345748, l='MpServer', x=225.98, y=51.16, z=338.75], EntityZombie['Zombie'/11346513, l='MpServer', x=288.50, y=33.00, z=308.50], EntitySquid['Squid'/11345744, l='MpServer', x=153.53, y=60.67, z=318.47], EntityBat['Bat'/11345747, l='MpServer', x=229.51, y=22.40, z=336.28], EntitySkeleton['Skeleton'/11345746, l='MpServer', x=225.50, y=17.00, z=336.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by P3pp3rF1y** [comment]
Have you also updated Reliquary version recently to a newer version? Because this is what happened to people who fired the shots before updating to version with potion shots. If that is the case I am not sure I would be able to fix that as I don't see a way, but want to make sure this is not happening for people who already started with a version that had potion shots included.

**Comment by P3pp3rF1y** [comment]
Closing as there was no response and this was only noticed by people who updated to a "newer" version in the past when projectiles got additional potion data.
