### ISSUE TITLE
Rending Gale Crashing Project Ozone 3

### ISSUE THREAD

**Issue by Thaikhan** [P3pp3rF1y/Reliquary#370]
Hello,

I'm playing the new pack - Project Ozone 3. I'm in a single player game. It appears that flying with the Rending Gale causes an irreversible desync from the in-game server. Within 5 minutes of flying, I can move around within the world but can no longer see within chests or interact with blocks in a way that saves. When I try to exit the game, the client freezes/crashes. There doesn't seem to be a useful crash report. The problem is reproducible (x5) and appears to only happen when flying with the Rending Gale. I looked through the related issues but they appeared older so I decided to submit a new one.

Please let me know if I can provide any particular information that would be more useful.

Thanks!

**Comment by P3pp3rF1y** [comment]
Are you sure it's not simply just world gen happening that's causing this? all rending gale does on flight is the same kind of stuff that any other movement does, it's just much faster than walking/running and probably a bit faster than elytra.
If you try the same with any kind of other fast speed thing do you get the same? I believe the modpack should have Botania so sojourner's sash or its upgraded variant and then just try to fly around in creative.

**Comment by Thaikhan** [comment]
That was one of my initial thoughts but unfortunately, I don't think it is. The problem even happens when flying back and forth between 4x4 chunk area and does not seem to happen with the angel ring which seems to have similar speed. I'll keep an eye out though and let you know if it happens with any other movement items.

**Comment by Saereth** [comment]
We are having this issue as well, server hung 3 times yesterday because of rending gale. No crashlog to provide just a stall log:

```
Stall report from 2019-03-21 07:50:29 -0400, 66 threads, stalled for at least 480000 ms.
Heap memory usage: 3405 / 4294 MB (max. 8303 MB).
Created by sampler 1.80 (MC 1.12).

"Server thread" #21 prio=5
RUNNABLE
        at net.minecraft.world.World.func_175720_a(World.java:1169)
        at net.minecraft.world.World.func_175688_a(World.java:1148)
        at xreliquary.items.ItemRendingGale.spawnFlightParticles(ItemRendingGale.java:403)
        at xreliquary.items.ItemRendingGale.onUsingTick(ItemRendingGale.java:242)
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097)
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
        - locked java.util.Collections$SynchronizedRandomAccessList@72ce788a
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:745)

```

next time this happens we'll try to profile it and see whats going on

**Comment by Frankawesome144** [comment]
I had a similar crash on our server... https://pastebin.com/bTP6CrSV 
I have no idea if its about how it makes you fly with such speed(tick acceleration? idk), or if it's the particle  effects(tried turning them off and it didn't help, we recreated this many times), or if somehow has to do with toggling downfall(that was in a previous crash log).

**Comment by mbaello** [comment]
Sorry if this is considered necro-ing, but this is still relevant. Currently playing FTB's Ultimate Reloaded pack which has Reliquary in it. I've made my own slightly detailed post about it on their issues page, but realized it would probably be better if directed to the Reliquary issues page instead (https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/249).

My own server has crashed about 4-5 times now due to Rending Gale and all of these crashes leave the server hanging until a (user-defined) tick limit is reached. Then the server is just presumed dead/crashed. 

https://paste.feed-the-beast.com/view/cc83dd3f

**Comment by vexcat** [comment]
It's possible for a division by 0 to occur in `spawnFlightParticles`, and it will cause `factor` within it to be +/-Infinity and hang the server. Changing the math here should fix this issue, no?
https://github.com/P3pp3rF1y/Reliquary/blob/1.12.x/src/main/java/xreliquary/items/ItemRendingGale.java#L395

**Comment by P3pp3rF1y** [comment]
Thanks for that @vexcat I didn't see it before but this is definitely what's happening and why the crashes happen. Just fixed the issue and will release soon.
