### ISSUE TITLE
[1.15.2] Huge String of Errors 

### ISSUE THREAD

**Issue by Ponleak** [P3pp3rF1y/Reliquary#402]
[2020-04-06-4.log](https://github.com/P3pp3rF1y/Reliquary/files/4446438/2020-04-06-4.log)
Here is the whole server log 

This repeating string of errors persists until my server crashes due to a StackOverflow error

**Comment by P3pp3rF1y** [comment]
I have these warnings fixed, but they really aren't the cause of your server crashing. - they only occur when an event is triggered - mob killed, player dying from fall, which doesn't occur that often (well at least in terms of server time and in terms of something that can actually cause anything like server slowdown or crash)

The real issue you have there is the leafdecay crash:

```
[06Apr2020 23:31:58.987] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: enemeez.simplefarming.block.growable.FruitLeavesBlock cannot be cast to net.minecraft.block.LeavesBlock
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2500/594983768@2bbbbf8c
		2: ASM: class net.silentchaos512.gear.event.GearEvents onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		3: ASM: class oreexcavation.handlers.EventHandler onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		4: ASM: net.minecraftforge.common.ForgeInternalHandler@198dfc18 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
java.lang.ClassCastException: enemeez.simplefarming.block.growable.FruitLeavesBlock cannot be cast to net.minecraft.block.LeavesBlock
	at net.olafkeijsers.fastleafdecay.FldScheduler.tick(FldScheduler.java:55)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by P3pp3rF1y** [comment]
the fix for the warnings is now released
