### ISSUE TITLE
Couldn't parse loot table minecraft:chests/simple_dungeon

### ISSUE THREAD

**Issue by shenniko** [P3pp3rF1y/Reliquary#458]
getting an error with loot chests:

Minecraft Version: 1.16.3
forge: forge-34.1.16
Mods version: Reliquary-1.16.3-1.3.4.1015.jar

[12Oct2020 20:45:37.438] [Worker-Main-11/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table minecraft:chests/simple_dungeon
java.lang.NullPointerException: null
	at net.minecraft.loot.LootTable.lambda$addPool$2(LootTable.java:207) ~[?:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_265]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361) ~[?:1.8.0_265]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_265]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516) ~[?:1.8.0_265]
	at net.minecraft.loot.LootTable.addPool(LootTable.java:207) ~[?:?]
	at xreliquary.init.ModLoot.lootLoad(ModLoot.java:34) ~[?:1.16.3-1.3.4.1015]
	at net.minecraftforge.eventbus.ASMEventHandler_120_ModLoot_lootLoad_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:653) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:827) ~[?:?]
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_265]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38) ~[?:?]
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_265]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_265]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_265]
[12Oct2020 20:45:37.474] [Worker-Main-11/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: chanceCubes.CCubesCore@1730d691 lootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		2: ASM: class xreliquary.init.ModLoot lootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		3: ASM: class com.teammetallurgy.aquaculture.init.AquaLootTables onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		4: ASM: class com.github.alexthe666.rats.server.events.CommonEvents onLootTableRolled(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		5: ASM: enemeez.simplefarming.events.LootTableHandler@414dd52b lootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
java.lang.NullPointerException
	at net.minecraft.loot.LootTable.lambda$addPool$2(LootTable.java:207)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
	at net.minecraft.loot.LootTable.addPool(LootTable.java:207)
	at xreliquary.init.ModLoot.lootLoad(ModLoot.java:34)
	at net.minecraftforge.eventbus.ASMEventHandler_120_ModLoot_lootLoad_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:653)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:827)
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

https://gist.githubusercontent.com/shenniko/26b7321e6a37bfde93f31601436d9722/raw/1cf16421a55b6191a0e837ce77b1210158587628/debug.log

**Comment by P3pp3rF1y** [comment]
I am not sure what's wrong for you as both in dev as well as in ATM 6 mod pack I don't see this happening and definitely can see Reliquary items included in vanilla chest loots. It's likely one of the core mods you have in your mod pack causing this issue. Probably best course of action is to narrow it down to what mod is causing the issue and report to them. Unless of course you can recreate this with just reliquary

**Comment by P3pp3rF1y** [comment]
I am closing this, if you are able to recreate with just reliquary feel free to reopen
