### ISSUE TITLE
There is a bug during my lanch the game

### ISSUE THREAD

**Issue by OneLanp** [P3pp3rF1y/Reliquary#543]
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.getEventClass(EventBus.java:220) ~[eventbus-4.0.0.jar:?] {}
-- MOD xreliquary --
Details:
	Mod File: reliquary-1.16.5-1.3.5.1100.jar
	Failure message: Reliquary (xreliquary) has failed to load correctly
		java.lang.IllegalStateException: Failed to resolve consumer event type: xreliquary.Reliquary$$Lambda$4953/0x0000000000000000@f2ead0c3
	Mod Version: 1.16.5-1.3.5.1100
	Mod Issue URL: https://github.com/p3pp3rF1y/reliquary/issues
	Exception message: java.lang.IllegalStateException: Failed to resolve consumer event type: xreliquary.Reliquary$$Lambda$4953/0x0000000000000000@f2ead0c3
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.getEventClass(EventBus.java:220) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.checkNotGeneric(EventBus.java:162) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:173) ~[eventbus-4.0.0.jar:?] {}
	at xreliquary.Reliquary.<init>(Reliquary.java:51) ~[xreliquary:1.16.5-1.3.5.1100] {re:classloading}
	at java.lang.J9VMInternals.newInstanceImpl(Native Method) ~[?:?] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3319/0x0000000000000000.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3547/0x0000000000000000.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

How can i solve the problem?
thanks

**Comment by P3pp3rF1y** [comment]
you're using OpenJ9 which is not supported by forge so you will need to switch to a different JVM and that will fix it for you.
