### ISSUE TITLE
Crash on startup (1.18.2)

### ISSUE THREAD

**Issue by MJpyroman** [P3pp3rF1y/Reliquary#555]
This happen when I'm trying to run my server
Thing is, game load just fine client side
Done some research, don't really know what's happening
thanks ~

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 19/03/2022 00:57
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.0.17-universal.jar%23120!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.0.17-universal.jar%23120!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220228.144236-srg.jar%23116!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.2-40.0.17.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD reliquary --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.17.jar%23118!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.17.jar%23117!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: net/minecraft/client/model/Model
		at reliquary.init.ModItems.<clinit>(ModItems.java:153) ~[reliquary-1.18.2-2.0.1.1129.jar%2394!/:1.18.2-2.0.1.1129] {re:classloading}
		at reliquary.Reliquary.<init>(Reliquary.java:57) ~[reliquary-1.18.2-2.0.1.1129.jar%2394!/:1.18.2-2.0.1.1129] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.17.jar%23118!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.17.jar%23117!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: reliquary-1.18.2-2.0.1.1129.jar
	Failure message: Reliquary (reliquary) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.18.2-2.0.1.1129
	Mod Issue URL: https://github.com/p3pp3rF1y/reliquary/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.model.Model
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at reliquary.init.ModItems.<clinit>(ModItems.java:153) ~[reliquary-1.18.2-2.0.1.1129.jar%2394!/:1.18.2-2.0.1.1129] {re:classloading}
	at reliquary.Reliquary.<init>(Reliquary.java:57) ~[reliquary-1.18.2-2.0.1.1129.jar%2394!/:1.18.2-2.0.1.1129] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.17.jar%23118!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.17.jar%23117!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2171060728 bytes (2070 MiB) / 3690987520 bytes (3520 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4,01
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1c60
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192,00
	Memory slot #2 clockSpeed (GHz): 2,13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192,00
	Memory slot #3 clockSpeed (GHz): 2,13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37589,38
	Virtual memory used (MB): 12357,41
	Swap memory total (MB): 4864,00
	Swap memory used (MB): 8,02
	JVM Flags: 1 total; -Xmx12G
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		Cucumber-1.18.2-5.1.0.jar                         |Cucumber Library              |cucumber                      |5.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		trashslot-forge-1.18.1-11.0.2.jar                 |TrashSlot                     |trashslot                     |11.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		netherportalfix-forge-1.18-9.0.0.jar              |NetherPortalFix               |netherportalfix               |9.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.2-9.5.2.141.jar                          |Just Enough Items             |jei                           |9.5.2.136           |COMMON_SET|Manifest: NOSIGNATURE
		ExtendedCrafting-1.18.2-4.1.0.jar                 |Extended Crafting             |extendedcrafting              |4.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		tesseract-1.0.25-mc1.18.jar                       |Tesseract                     |tesseract                     |1.0.25              |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.0.0.jar                 |Waystones                     |waystones                     |10.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+7.jar                   |Clumps                        |clumps                        |8.0.0+7             |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.18.2-5.8.0.jar                       |Journeymap                    |journeymap                    |5.8.0               |COMMON_SET|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.0.0.jar      |CookingForBlockheads          |cookingforblockheads          |12.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+17.jar               |Controlling                   |controlling                   |9.0+17              |COMMON_SET|Manifest: NOSIGNATURE
		ReAuth-1.18-Forge-4.0.0.jar                       |ReAuth                        |reauth                        |4.0.0               |COMMON_SET|Manifest: 3d:06:1e:e5:da:e2:ff:ae:04:00:be:45:5b:ff:fd:70:65:00:67:0b:33:87:a6:5f:af:20:3c:b6:a1:35:ca:7e
		SimpleStorageNetwork-1.18.2-1.6.1.jar             |Simple Storage Network        |storagenetwork                |1.18.2-1.6.1        |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		configured-1.5.3-1.18.1.jar                       |Configured                    |configured                    |1.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		curioofundying-forge-1.18-5.3.0.0.jar             |Curio of Undying              |curioofundying                |1.18-5.3.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		upgradednetherite_items-1.18.2-3.2.0.0-release.jar|Upgraded Netherite : Items    |upgradednetherite_items       |1.18.2-3.2.0.0-relea|COMMON_SET|Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.18.2-10.0.0.jar      |Farming for Blockheads        |farmingforblockheads          |10.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.0.7.jar                 |Bookshelf                     |bookshelf                     |13.0.7              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		pneumaticcraft-repressurized-1.18.2-3.1.1-61.jar  |PneumaticCraft: Repressurized |pneumaticcraft                |1.18.2-3.1.1-61     |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.15.16.556.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.15.16.556  |COMMON_SET|Manifest: NOSIGNATURE
		bonsaitrees3-3.1.0.jar                            |Bonsai Trees 3                |bonsaitrees3                  |3.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		DarkUtilities-Forge-1.18.2-10.0.1.jar             |DarkUtilities                 |darkutils                     |10.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		balm-3.0.1+0.jar                                  |Balm                          |balm                          |3.0.1+0             |COMMON_SET|Manifest: NOSIGNATURE
		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.14.0.155.jar         |Just Enough Resources         |jeresources                   |0.14.0.155          |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-6.2.57-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.57              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.0.17-universal.jar                |Forge                         |forge                         |40.0.17             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		shetiphiancore-1.18-3.10.5.jar                    |ShetiPhian-Core               |shetiphiancore                |3.10.5              |COMMON_SET|Manifest: NOSIGNATURE
		upgradednetherite-1.18.2-4.2.0.1-beta.jar         |Upgraded Netherite            |upgradednetherite             |1.18.2-4.2.0.1-beta |COMMON_SET|Manifest: NOSIGNATURE
		MysticalAgriculture-1.18.2-5.1.0.jar              |Mystical Agriculture          |mysticalagriculture           |5.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		MysticalAgradditions-1.18.2-5.1.0.jar             |Mystical Agradditions         |mysticalagradditions          |5.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		craftingtweaks-forge-1.18.1-14.0.2.jar            |CraftingTweaks                |craftingtweaks                |14.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		ZeroCore2-1.18.2-2.1.15.jar                       |Zero CORE 2                   |zerocore                      |1.18.2-2.1.15       |COMMON_SET|Manifest: NOSIGNATURE
		server-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
		TipTheScales-forge-1.18.2-5.0.5.jar               |TipTheScales                  |tipthescales                  |5.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.2-10.0.2.jar   |EnchantmentDescriptions       |enchdesc                      |10.0.2              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		theoneprobe-1.18-5.1.0.jar                        |The One Probe                 |theoneprobe                   |1.18-5.1.0          |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.93.jar            |TerraBlender                  |terrablender                  |1.18.2-1.1.0.93     |COMMON_SET|Manifest: NOSIGNATURE
		entangled-1.3.10-mc1.18.jar                       |Entangled                     |entangled                     |1.3.10              |COMMON_SET|Manifest: NOSIGNATURE
		endertanks-1.18-1.11.4.jar                        |EnderTanks                    |endertanks                    |1.11.4              |COMMON_SET|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.0.13_mc1.18.2.jar          |Ambient Sounds                |ambientsounds                 |3.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.107-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.107   |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.0_mc1.18.2.jar            |CreativeCore                  |creativecore                  |2.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.16b-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.16b             |COMMON_SET|Manifest: NOSIGNATURE
		Ding-1.18-1.3.0.jar                               |Ding                          |ding                          |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		pipez-1.18.2-1.0.0.jar                            |Pipez                         |pipez                         |1.18.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.6.3.jar                   |Curios API                    |curios                        |1.18.2-5.0.6.3      |COMMON_SET|Manifest: NOSIGNATURE
		reliquary-1.18.2-2.0.1.1129.jar                   |Reliquary                     |reliquary                     |1.18.2-2.0.1.1129   |ERROR     |Manifest: NOSIGNATURE
		Patchouli-1.18.2-66.jar                           |Patchouli                     |patchouli                     |1.18.2-66           |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2foodcore-1.18.2-1.0.0.jar                   |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		itemcollectors-1.1.4-mc1.18.jar                   |Item Collectors               |itemcollectors                |1.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		PigPen-Forge-1.18.2-8.0.1.jar                     |PigPen                        |pigpen                        |8.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughProfessions-1.18.2-1.2.2.jar            |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |COMMON_SET|Manifest: NOSIGNATURE
		Quark-3.2-344.jar                                 |Quark                         |quark                         |3.2-344             |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.1.1.jar                  |Storage Drawers               |storagedrawers                |10.1.1              |COMMON_SET|Manifest: NOSIGNATURE
		time-in-a-bottle-2.1.0-mc1.18.1.jar               |Time In A Bottle              |tiab                          |2.1.0-mc1.18.1      |COMMON_SET|Manifest: NOSIGNATURE
		enderchests-1.18-1.9.3.jar                        |EnderChests                   |enderchests                   |1.9.3               |COMMON_SET|Manifest: NOSIGNATURE
		angelring-1.18-1.5.0.jar                          |Angel Ring                    |angelring                     |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		DrawersTooltip-1.18.2-forge-5.0.0.jar             |Drawers Tooltip               |drawerstooltip                |5.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		libnonymous-2.1.0.jar                             |libnonymous                   |libnonymous                   |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		elevatorid-1.18.2-1.8.4.jar                       |Elevator Mod                  |elevatorid                    |1.18.2-1.8.4        |COMMON_SET|Manifest: NOSIGNATURE
		Runelic-Forge-1.18.2-11.0.1.jar                   |Runelic                       |runelic                       |11.0.1              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		upgradedcore-1.18.2-3.2.0.0-release.jar           |Upgraded Core                 |upgradedcore                  |1.18.2-3.2.0.0-relea|COMMON_SET|Manifest: NOSIGNATURE
		architectury-4.1.32.jar                           |Architectury                  |architectury                  |4.1.32              |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-4.2.0-forge.jar                       |Ferrite Core                  |ferritecore                   |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		cc-tweaked-1.18.2-1.100.3.jar                     |CC: Tweaked                   |computercraft                 |1.100.3             |COMMON_SET|Manifest: NOSIGNATURE
		upgradednetherite_ultimate-1.18.2-3.2.0.0-release.|Upgraded Netherite : Ultimerit|upgradednetherite_ultimate    |1.18.2-3.2.0.0-relea|COMMON_SET|Manifest: NOSIGNATURE
		ExtremeReactors2-1.18.2-2.0.40.jar                |Extreme Reactors              |bigreactors                   |1.18.2-2.0.40       |COMMON_SET|Manifest: NOSIGNATURE
		light-overlay-6.0.5-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		trashcans-1.0.12-mc1.18.jar                       |Trash Cans                    |trashcans                     |1.0.12              |COMMON_SET|Manifest: NOSIGNATURE
		extremeSoundMuffler-3.24_Forge-1.18.1.jar         |Extreme Sound Muffler         |extremesoundmuffler           |3.24_forge-1.18.1   |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-28.jar                              |FastLeafDecay                 |fastleafdecay                 |28                  |COMMON_SET|Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.2-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v1           |COMMON_SET|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		Cyclic-1.18.2-1.6.17.jar                          |Cyclic                        |cyclic                        |1.18.2-1.6.17       |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: e8071c07-1117-41e7-bc1b-13c16434df32
	FML: 40.0
	Forge: net.minecraftforge:40.0.17

**Comment by P3pp3rF1y** [comment]
Solved in the latest release on curseforge
