### ISSUE TITLE
[Bug] Reliquary pedestal crashes.

### ISSUE THREAD

**Issue by haltalt** [P3pp3rF1y/Reliquary#575]
I got the following crash when putting the following sword into a pedestal.
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:906) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class reliquary.blocks.tile.PedestalBlockEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.core.BlockPos getBlockPos()' of interface reliquary.api.IPedestal.
	at reliquary.pedestal.wrappers.PedestalMeleeWeaponWrapper.update(PedestalMeleeWeaponWrapper.java:29) ~[reliquary-1.18.2-2.0.6.1135.jar%2370!/:1.18.2-2.0.6.1135]
	at reliquary.blocks.tile.PedestalBlockEntity.lambda$serverTick$5(PedestalBlockEntity.java:202) ~[reliquary-1.18.2-2.0.6.1135.jar%2370!/:1.18.2-2.0.6.1135]
	at reliquary.blocks.tile.PedestalBlockEntity.executeOnActionItem(PedestalBlockEntity.java:138) ~[reliquary-1.18.2-2.0.6.1135.jar%2370!/:1.18.2-2.0.6.1135]
	at reliquary.blocks.tile.PedestalBlockEntity.serverTick(PedestalBlockEntity.java:202) ~[reliquary-1.18.2-2.0.6.1135.jar%2370!/:1.18.2-2.0.6.1135]
	at reliquary.blocks.PedestalBlock.lambda$getTicker$2(PedestalBlock.java:102) ~[reliquary-1.18.2-2.0.6.1135.jar%2370!/:1.18.2-2.0.6.1135]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2374!/:?]
	... 5 more
I'm on 1.18.2 forge. List of mods:
![image](https://user-images.githubusercontent.com/91082490/171937647-f59b16f7-f85b-4af7-8fe8-0da7c50d554d.png)

**Comment by Schyler-Lowry** [comment]
youre using an old version of reliquary. I had this same issue. Update to the latest version and the issue should be gone.

**Comment by P3pp3rF1y** [comment]
exactly as @DrGetgood says, just update to latest

**Comment by haltalt** [comment]
> youre using an old version of reliquary. I had this same issue. Update to the latest version and the issue should be gone.

Forge tells me I am on the newest one... (updated: 6 days ago). Web curseforge says last update was 6 days ago, but the version doesn't match. Do I need to download from the web, or what?

**Comment by Schyler-Lowry** [comment]
> 

Looking at your screenshot it shows you have version 11**35**. Most recent is 11**37**. Download it directly from curseforge. Latest is May 29th, reliquary-1.18.2-2.0.7.11**37**.jar
