### ISSUE TITLE
[BUG] Using Buster Shot when installing Curtain Mod can cause the game to crash

### ISSUE THREAD

**Issue by Gu-ZT** [P3pp3rF1y/Reliquary#631]
## OS Version
Windows

## Version Details
1.18.2-2.0.19.1161

## To Reproduce
* Setup [Curtain](https://github.com/Gu-ZT/Curtain) and [Reliquary](https://github.com/P3pp3rF1y/Reliquary)
* Enable optimizedTNT rule
* Using a Hunter's Handgun to Load Buster Shot
* shoot
* crash

## Crash Report
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023/5/7 上午4:07
Description: Ticking entity

java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class it.unimi.dsi.fastutil.objects.ObjectArrayList (java.util.ArrayList is in module java.base of loader 'bootstrap'; it.unimi.dsi.fastutil.objects.ObjectArrayList is in module it.unimi.dsi.fastutil@8.5.6 of loader 'MC-BOOTSTRAP' @b7dd107)
	at dev.dubhe.curtain.utils.OptimizedExplosion.doExplosionB(OptimizedExplosion.java:216) ~[curtain-mc1.18.2-1.2.2.jar%2353!/:1.2.2] {re:mixin,re:classloading}
	at net.minecraft.world.level.Explosion.handler$zbk000$onExplosionB(Explosion.java:1053) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,re:classloading,pl:mixin:APP:curtain.mixins.json:ExplosionAccessor,pl:mixin:APP:curtain.mixins.json:rules.optimized_tnt.ExplosionMixin,pl:mixin:A}
	at net.minecraft.world.level.Explosion.m_46075_(Explosion.java) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,re:classloading,pl:mixin:APP:curtain.mixins.json:ExplosionAccessor,pl:mixin:APP:curtain.mixins.json:rules.optimized_tnt.ExplosionMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_7703_(ServerLevel.java:966) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46518_(Level.java:515) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:curtain.mixins.json:rules.cactus.LevelMixin,pl:mixin:A}
	at reliquary.entities.ConcussiveExplosion.customBusterExplosion(ConcussiveExplosion.java:127) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.BusterShotEntity.doBurstEffect(BusterShotEntity.java:26) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.ShotEntityBase.ricochet(ShotEntityBase.java:366) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.ShotEntityBase.groundImpact(ShotEntityBase.java:312) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.ShotEntityBase.m_6532_(ShotEntityBase.java:472) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.ShotEntityBase.m_8119_(ShotEntityBase.java:206) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:curtain.mixins.json:rules.cactus.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dev.dubhe.curtain.utils.OptimizedExplosion.doExplosionB(OptimizedExplosion.java:216) ~[curtain-mc1.18.2-1.2.2.jar%2353!/:1.2.2] {re:mixin,re:classloading}
	at net.minecraft.world.level.Explosion.handler$zbk000$onExplosionB(Explosion.java:1053) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,re:classloading,pl:mixin:APP:curtain.mixins.json:ExplosionAccessor,pl:mixin:APP:curtain.mixins.json:rules.optimized_tnt.ExplosionMixin,pl:mixin:A}
	at net.minecraft.world.level.Explosion.m_46075_(Explosion.java) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,re:classloading,pl:mixin:APP:curtain.mixins.json:ExplosionAccessor,pl:mixin:APP:curtain.mixins.json:rules.optimized_tnt.ExplosionMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_7703_(ServerLevel.java:966) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46518_(Level.java:515) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:curtain.mixins.json:rules.cactus.LevelMixin,pl:mixin:A}
	at reliquary.entities.ConcussiveExplosion.customBusterExplosion(ConcussiveExplosion.java:127) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.BusterShotEntity.doBurstEffect(BusterShotEntity.java:26) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.ShotEntityBase.ricochet(ShotEntityBase.java:366) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.ShotEntityBase.groundImpact(ShotEntityBase.java:312) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.ShotEntityBase.m_6532_(ShotEntityBase.java:472) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at reliquary.entities.shot.ShotEntityBase.m_8119_(ShotEntityBase.java:206) ~[reliquary-1.18.2-2.0.19.1161.jar%2354!/:1.18.2-2.0.19.1161] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:curtain.mixins.json:rules.cactus.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: reliquary:buster_shot (reliquary.entities.shot.BusterShotEntity)
	Entity ID: 53
	Entity Name: entity.reliquary.buster_shot
	Entity's Exact location: 19.74, -59.89, -7.18
	Entity's Block location: World: (19,-60,-8), Section: (at 3,4,8 in 1,-4,-1; chunk contains blocks 16,-64,-16 to 31,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.62, 0.33, -0.97
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:curtain.mixins.json:rules.cactus.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['WeiAL'/16, l='ServerLevel[新的世界]', x=17.14, y=-60.00, z=-3.38]]
	Chunk stats: 2809
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 25576 game time, 25576 day time
	Level name: 新的世界
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 17884 (now: true), thunder time: 10557 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.4, Alibaba
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Alibaba
	Memory: 533466576 bytes (508 MiB) / 1744830464 bytes (1664 MiB) up to 7348420608 bytes (7008 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 4800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.89
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f15
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2824
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 57213.32
	Virtual memory used (MB): 21364.18
	Swap memory total (MB): 40960.00
	Swap memory used (MB): 1933.21
	JVM Flags: 11 total; -Xmx7000m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['WeiAL'/16, l='ServerLevel[新的世界]', x=17.14, y=-60.00, z=-3.38]]
	Data Packs: vanilla, mod:forge, mod:reliquary (incompatible), mod:curtain (incompatible)
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.2-40.2.1-universal.jar                 |Forge                         |forge                         |40.2.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		reliquary-1.18.2-2.0.19.1161.jar             |Reliquary                     |reliquary                     |1.18.2-2.0.19.1161  |DONE      |Manifest: NOSIGNATURE
		curtain-mc1.18.2-1.2.2.jar                 |Curtain                       |curtain                       |1.2.2               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: e1921515-6739-4295-9ae5-a4dfbefa17ad
	FML: 40.2
	Forge: net.minecraftforge:40.2.1
```

**Comment by P3pp3rF1y** [comment]
You will need to report this to Curtain mod. All that Reliquary does is just call vanilla method to cause explosion and curtain seems to make a change there that's incompatible with how that method works or with some other change some other mod in your modpack does. Anyway there's nothing that can be fixed on Reliquary side here.
