### ISSUE TITLE
MobCharmItem causing server crash

### ISSUE THREAD

**Issue by Plaaasma** [P3pp3rF1y/Reliquary#671]
I run a small server that has reliquary on it and every now and then it crashes with the following error message:
`java.lang.NullPointerException: Cannot invoke "java.util.Set.contains(Object)" because the return value of "java.util.Map.get(Object)" is null
	at TRANSFORMER/reliquary@1.20.1-2.0.39.1211/reliquary.items.MobCharmItem$CharmInventoryHandler.playerHasMobCharm(MobCharmItem.java:254)
	at TRANSFORMER/reliquary@1.20.1-2.0.39.1211/reliquary.items.MobCharmItem.isMobCharmPresent(MobCharmItem.java:169)
	at TRANSFORMER/reliquary@1.20.1-2.0.39.1211/reliquary.items.MobCharmItem.lambda$onLivingUpdate$1(MobCharmItem.java:122)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at TRANSFORMER/reliquary@1.20.1-2.0.39.1211/reliquary.items.MobCharmItem.onLivingUpdate(MobCharmItem.java:121)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.21/net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:264)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2258)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_8119_(Mob.java:337)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:840)
`

If you need any more information from me please let me know.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release
