### ISSUE TITLE
Crash after few minutes

### ISSUE THREAD

**Issue by WildNightFoxy** [P3pp3rF1y/Reliquary#677]
Reliquary (reliquary), Version: 1.20.1-2.0.40.1224
		Issue tracker URL: https://github.com/p3pp3rF1y/reliquary/issues
		at TRANSFORMER/reliquary@1.20.1-2.0.40.1224/reliquary.items.MobCharmItem$CharmInventoryHandler.playerHasMobCharm(MobCharmItem.java:253)
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
	at reliquary.items.MobCharmItem$CharmInventoryHandler.playerHasMobCharm(MobCharmItem.java:253) ~[reliquary-1.20.1-2.0.40.1224.jar%23407!/:1.20.1-2.0.40.1224] {re:classloading}
	at reliquary.items.MobCharmItem.isMobCharmPresent(MobCharmItem.java:169) ~[reliquary-1.20.1-2.0.40.1224.jar%23407!/:1.20.1-2.0.40.1224] {re:classloading}
	at reliquary.items.MobCharmItem.lambda$onLivingUpdate$1(MobCharmItem.java:122) ~[reliquary-1.20.1-2.0.40.1224.jar%23407!/:1.20.1-2.0.40.1224] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at reliquary.items.MobCharmItem.onLivingUpdate(MobCharmItem.java:121) ~[reliquary-1.20.1-2.0.40.1224.jar%23407!/:1.20.1-2.0.40.1224] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2381!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2381!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2381!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2381!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:264) ~[forge-1.20.1-47.2.23-universal.jar%23446!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.hammerlib.json:ForgeHooksMixin,pl:mixin:APP:apoli.mixins.json:forge.ForgeHooksMixin,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2258) ~[client-1.20.1-20230612.114412-srg.jar%23441!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:unionlib.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:additionalentityattributes.mixins.json:common.LivingEntityMixin,pl:mixin:APP:aether.mixins.json:common.LivingEntityMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LivingEntityAccessor,pl:mixin:APP:apoli.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:lost_aether_content.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity,pl:mixin:APP:relics.mixins.json:LivingEntityMixin,pl:mixin:APP:beyond_earth.mixin.json:LivingSprinting,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_LivingEntity,pl:mixin:APP:botania_xplat.mixins.json:LivingEntityAccessor,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:APP:attributeslib.mixins.json:LivingEntityMixin,pl:mixin:APP:survive.mixins.json:LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat1194plus.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.artifacts.common.json:item.hurtsound.LivingEntityMixin,pl:mixin:APP:mixins.artifacts.common.json:item.hurtsound.client.LivingEntityMixin,pl:mixin:APP:simplyswords-common.mixins.json:LivingEntityMixin,pl:mixin:APP:apugli.mixins.json:common.LivingEntityMixin,pl:mixin:APP:apugli.mixins.json:common.accessor.LivingEntityAccessor,pl:mixin:APP:apugli.forge.mixins.json:common.LivingEntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:LivingEntityMixin,pl:mixin:APP:canary.mixins.json:alloc.enum_values.living_entity.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinLivingEntity,pl:mixin:APP:pehkui.mixins.json:compat115plus.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23441!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:aether.mixins.json:common.MobMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:botania_xplat.mixins.json:MobAccessor,pl:mixin:APP:pehkui.mixins.json:MobEntityMixin,pl:mixin:APP:mixins.artifacts.common.json:accessors.MobAccessor,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.MobMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.MobMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.MobEntityMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23441!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:embeddium.mixins.json:features.render.world.ClientLevelMixin,pl:mixin:APP:dynamiclightsreforged.mixins.json:ClientWorldMixin,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:unionlib.mixins.json:client.ClientLevelMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:mixins.hammerlib.json:client.ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23441!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256) ~[client-1.20.1-20230612.114412-srg.jar%23441!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:embeddium.mixins.json:features.render.world.ClientLevelMixin,pl:mixin:APP:dynamiclightsreforged.mixins.json:ClientWorldMixin,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:unionlib.mixins.json:client.ClientLevelMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:mixins.hammerlib.json:client.ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23441!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:collections.entity_ticking.EntityTickListMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254) ~[client-1.20.1-20230612.114412-srg.jar%23441!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:embeddium.mixins.json:features.render.world.ClientLevelMixin,pl:mixin:APP:dynamiclightsreforged.mixins.json:ClientWorldMixin,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:unionlib.mixins.json:client.ClientLevelMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:mixins.hammerlib.json:client.ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by WildNightFoxy** [comment]
Oh, i see a lot of closed issues with similar problems. Sadly.

**Comment by P3pp3rF1y** [comment]
well the issue is some mod is parallel ticking entities which is bound to create problems like this, I will change the collection there to get rid of this annoying thing, but it's likely you will have issues with other stuff as well
